name: Arena Bot

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Type RUN to start arena bot"
        required: true
        default: "RUN"

jobs:
  run-arena:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    strategy:
      fail-fast: false
      max-parallel: 11

      matrix:
        include:
          - id: 25
            game_id_secret: GAME_ID_25
            game_password_secret: GAME_PASSWORD_25

          - id: 28
            game_id_secret: GAME_ID_28
            game_password_secret: GAME_PASSWORD_28

          - id: 29
            game_id_secret: GAME_ID_29
            game_password_secret: GAME_PASSWORD_29

          - id: 30
            game_id_secret: GAME_ID_30
            game_password_secret: GAME_PASSWORD_30

          - id: 33
            game_id_secret: GAME_ID_33
            game_password_secret: GAME_PASSWORD_33

          - id: 34
            game_id_secret: GAME_ID_34
            game_password_secret: GAME_PASSWORD_34

          - id: 35
            game_id_secret: GAME_ID_35
            game_password_secret: GAME_PASSWORD_35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate manual trigger
        run: |
          echo "Mode: ${{ github.event.inputs.run_mode }}"
          if [ "${{ github.event.inputs.run_mode }}" != "RUN" ]; then
            echo "Not authorized run. Exiting."
            exit 1
          fi

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Project
        run: mvn -U -B clean compile -Dmaven.wagon.http.retryHandler.count=5

      - name: Run Arena Bot
        env:
          GAME_ID: ${{ secrets[matrix.game_id_secret] }}
          GAME_PASSWORD: ${{ secrets[matrix.game_password_secret] }}
        run: mvn -B exec:java -Dexec.mainClass=ArenaMain
