name: Arena Bot

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Type RUN to start arena bot"
        required: true
        default: "RUN"

jobs:
  run-arena:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    strategy:
      fail-fast: false
      max-parallel: 11

      matrix:
        include:
          - id: 1
            game_id_secret: GAME_ID_1
            game_password_secret: GAME_PASSWORD_1

          - id: 2
            game_id_secret: GAME_ID_2
            game_password_secret: GAME_PASSWORD_2

          - id: 3
            game_id_secret: GAME_ID_3
            game_password_secret: GAME_PASSWORD_3

          - id: 4
            game_id_secret: GAME_ID_4
            game_password_secret: GAME_PASSWORD_4

          - id: 5
            game_id_secret: GAME_ID_5
            game_password_secret: GAME_PASSWORD_5

          - id: 6
            game_id_secret: GAME_ID_6
            game_password_secret: GAME_PASSWORD_6

          - id: 10
            game_id_secret: GAME_ID_10
            game_password_secret: GAME_PASSWORD_10

          - id: 11
            game_id_secret: GAME_ID_11
            game_password_secret: GAME_PASSWORD_11

          - id: 20
            game_id_secret: GAME_ID_20
            game_password_secret: GAME_PASSWORD_20

          - id: 24
            game_id_secret: GAME_ID_24
            game_password_secret: GAME_PASSWORD_24

          - id: 25
            game_id_secret: GAME_ID_25
            game_password_secret: GAME_PASSWORD_25

          - id: 28
            game_id_secret: GAME_ID_28
            game_password_secret: GAME_PASSWORD_28

          - id: 29
            game_id_secret: GAME_ID_29
            game_password_secret: GAME_PASSWORD_29

          - id: 30
            game_id_secret: GAME_ID_30
            game_password_secret: GAME_PASSWORD_30

          - id: 33
            game_id_secret: GAME_ID_33
            game_password_secret: GAME_PASSWORD_33

          - id: 34
            game_id_secret: GAME_ID_34
            game_password_secret: GAME_PASSWORD_34

          - id: 35
            game_id_secret: GAME_ID_35
            game_password_secret: GAME_PASSWORD_35

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate manual trigger
        run: |
          echo "Mode: ${{ github.event.inputs.run_mode }}"
          if [ "${{ github.event.inputs.run_mode }}" != "RUN" ]; then
            echo "Not authorized run. Exiting."
            exit 1
          fi

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Project
        run: mvn -B clean compile

      - name: Run Arena Bot
        env:
          GAME_ID: ${{ secrets[matrix.game_id_secret] }}
          GAME_PASSWORD: ${{ secrets[matrix.game_password_secret] }}
        run: mvn -B exec:java -Dexec.mainClass=ArenaMain
